export const INDIVIDUALS_INTRO =
  "We advise individuals on high-stakes legal matters involving property, technology, and digital risk, with a practical and protective approach.";

export const INDIVIDUAL_SERVICES = [
  {
    slug: "digital-asset-protection",
    title: "Digital Asset Protection",
    blurb:
      "Digital assets require intentional legal planning and risk management. We advise individuals on protecting, documenting, and responding to risks involving digital assets, online accounts, and digital credentials.",
    note:
      "This includes advisory support following unauthorized access, fraud, or loss, without guaranteeing recovery outcomes.",
    videoSrc: "/digital-asset.mp4",
    challenges: [
      "Unauthorized access, fraud, or loss: individuals need immediate legal guidance and response planning",
      "Digital asset documentation gaps: incomplete records can weaken protection and response efforts",
      "Online account and credential risk: exposed credentials can increase legal and practical risk",
      "Lack of structured planning: digital assets can remain vulnerable without clear risk management steps",
    ],
    services: [
      "Digital asset protection advisory",
      "Documentation and record-keeping guidance",
      "Advisory support following unauthorized access, fraud, or loss",
      "Risk management and response planning",
      "Ongoing advisory",
    ],
  },
  {
    slug: "real-estate",
    title: "Estates",
    blurb:
      "We assist individuals and families with wills, powers of attorney, estate planning, and the administration of estates. Our goal is to provide clarity, protection, and peace of mind whether you are planning for the future or navigating the responsibilities that follow a loved one's passing.",
    videoSrc: "/real estate 3.2.mp4",
    challenges: [
      "Unclear or outdated estate plans: individuals often struggle to create legally enforceable wills or to keep documents current with life changes.",
      "Family disputes and uncertainty: without clear instructions, families face confusion, conflict, or costly court proceedings.",
      "Executor responsibilities: executors may feel overwhelmed by legal, financial, and administrative obligations.",
      "Asset distribution complexities: blended families, business interests, real estate, or cross-border assets can complicate planning and administration.",
      "Urgent or compassionate situations: sudden illness or unexpected loss creates the need for fast, reliable legal support.",
    ],
    services: [
      { kind: "heading", name: "Wills and Powers of Attorney" },
      { kind: "subitem", name: "Drafting and updating wills" },
      { kind: "subitem", name: "Powers of attorney for property and personal care" },
      { kind: "heading", name: "Estate Planning" },
      {
        kind: "subitem",
        name: "Structuring asset distribution to minimize conflict and protect beneficiaries",
      },
      { kind: "subitem", name: "Planning for blended families" },
      { kind: "subitem", name: "Business succession considerations" },
      { kind: "subitem", name: "Trusts and guardianship planning" },
      { kind: "heading", name: "Estate Administration" },
      { kind: "subitem", name: "Guiding executors through probate" },
      { kind: "subitem", name: "Assisting with asset gathering and distribution" },
      { kind: "subitem", name: "Managing creditor claims and beneficiary communications" },
      { kind: "subitem", name: "Resolving disputes and providing legal risk management" },
      { kind: "heading", name: "Ongoing Advisory" },
      { kind: "subitem", name: "Updates to existing plans" },
      {
        kind: "subitem",
        name: "Guidance during life changes (marriage, divorce, births, acquisitions)",
      },
      { kind: "subitem", name: "Long-term strategic planning support" },
    ],
  },
  {
    slug: "estates",
    title: "Estates",
    blurb:
      "We assist individuals and families with wills, powers of attorney, estate planning, and the administration of estates. Our goal is to provide clarity, protection, and peace of mind whether you are planning for the future or navigating the responsibilities that follow a loved one's passing.",
    challenges: [
      "Unclear or outdated estate plans: individuals often struggle to create legally enforceable wills or to keep documents current with life changes",
      "Family disputes and uncertainty: without clear instructions, families face confusion, conflict, or costly court proceedings",
      "Executor responsibilities: executors may feel overwhelmed by legal, financial, and administrative obligations",
      "Asset distribution complexities: blended families, business interests, real estate, or cross-border assets can complicate planning and administration",
      "Urgent or compassionate situations: sudden illness or unexpected loss creates the need for fast, reliable legal support",
    ],
    services: [
      "Wills and powers of attorney",
      "Drafting and updating wills",
      "Powers of attorney for property and personal care",
      "Estate planning",
      "Structuring asset distribution to minimize conflict and protect beneficiaries",
      "Planning for blended families",
      "Business succession considerations",
      "Trusts and guardianship planning",
      "Estate administration",
      "Guiding executors through probate",
      "Assisting with asset gathering and distribution",
      "Managing creditor claims and beneficiary communications",
      "Resolving disputes and providing legal risk management",
      "Ongoing advisory",
      "Updates to existing plans",
      "Guidance during life changes (marriage, divorce, births, acquisitions)",
      "Long-term strategic planning support",
    ],
  },
  {
    slug: "family-law",
    title: "Family",
    blurb:
      "Family transitions - separation, divorce, and the reorganization of family life - carry significant legal, financial, and personal consequences. We provide clear, strategic legal counsel to individuals navigating these changes, with particular focus on clients whose circumstances involve property, business interests, estates, or cross-border complexity.",
    blurb2:
      "Our approach is direct and solutions-oriented. We help clients understand their rights and obligations, protect their financial interests, and reach resolutions that are durable and fair - whether through negotiation, mediation, or litigation.",
    challenges: [
      "Property and asset division: separating parties often face disputes over the equalization of net family property, including real estate, business interests, investment portfolios, and digital assets.",
      "Spousal and child support: calculating, negotiating, and enforcing support obligations under the Divorce Act and Family Law Act requires precision and an understanding of the financial picture on both sides.",
      "Parenting arrangements: determining decision-making responsibility and parenting time in a way that reflects the child's best interests while protecting the client's parental rights.",
      "Cohabitation and marriage contracts: individuals entering relationships with significant assets, business interests, or cross-border ties require agreements that will hold.",
      "International and cross-border matters: clients with property, assets, or family ties across jurisdictions - including within the Caribbean - face additional legal complexity that requires counsel with cross-border experience.",
      "Intersection with estates and business: separation often triggers the need to update wills, powers of attorney, and corporate structures - areas we address as part of an integrated approach.",
    ],
    services: [
      { kind: "heading", name: "Separation and Divorce" },
      { kind: "subitem", name: "Advice on rights and obligations upon separation" },
      { kind: "subitem", name: "Negotiation and drafting of separation agreements" },
      { kind: "subitem", name: "Uncontested divorce applications" },
      { kind: "subitem", name: "Contested divorce proceedings" },
      { kind: "heading", name: "Division of Property" },
      { kind: "subitem", name: "Equalization of net family property" },
      { kind: "subitem", name: "Valuation and treatment of business interests" },
      { kind: "subitem", name: "Real estate and investment asset division" },
      { kind: "subitem", name: "Excluded property and inheritance claims" },
      { kind: "heading", name: "Support" },
      {
        kind: "subitem",
        name: "Spousal support - initial orders, variations, and enforcement",
      },
      {
        kind: "subitem",
        name: "Child support under the Federal Child Support Guidelines",
      },
      { kind: "subitem", name: "Disclosure obligations and income determination" },
      { kind: "heading", name: "Parenting" },
      { kind: "subitem", name: "Parenting plans and decision-making arrangements" },
      { kind: "subitem", name: "Parenting time schedules" },
      { kind: "subitem", name: "Relocation and mobility matters" },
      { kind: "subitem", name: "Variation of existing orders" },
      { kind: "heading", name: "Domestic Contracts" },
      { kind: "subitem", name: "Marriage contracts (prenuptial agreements)" },
      { kind: "subitem", name: "Cohabitation agreements" },
      { kind: "subitem", name: "Separation agreements" },
      { kind: "subitem", name: "Independent legal advice" },
      { kind: "heading", name: "Ongoing Advisory" },
      {
        kind: "subitem",
        name: "Post-separation updates to wills and powers of attorney",
      },
      { kind: "subitem", name: "Corporate restructuring following separation" },
      {
        kind: "subitem",
        name: "Long-term planning support for blended families",
      },
    ],
  },
  {
    slug: "immigration",
    title: "Immigration",
    videoSrc: "/images/immigration.mp4",
    blurb:
      "Navigating Canada's immigration system can be complex and overwhelming. For businesses hiring global talent or entering the Canadian market, Mears Law provides strategic, efficient, and compliant solutions to help you achieve your immigration goals.",
    challenges: [
      "Confusing Application Processes: Clients struggle with eligibility and procedures",
      "Delays & Compliance Risks: Missed deadlines or incomplete applications lead to costly delays",
      "Employer Obligations: Challenges meeting compliance standards when hiring foreign workers and relocating key management personnel",
      "Changing Regulations: Immigration laws evolve quickly, creating uncertainty",
    ],
    services: [
      "Business Immigration",
      "Work Permits & Employer Compliance",
      "Permanent Residency & Citizenship",
      "Appeals & Dispute Resolution",
      "Ongoing Advisory",
    ],
  },
];
